name: Deploy local site

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: local
    steps:
      - name: Checkout
        run: git clone "${{ github.server_url }}/${{ github.repository }}.git" .
      - name: Build site
        run: uvx --from 'git+${{ github.server_url }}/BritoAlv/quarto_custom.git@main' quarto-custom --config quarto_custom_site.toml --deploy
      - name: Deploy
        run: |
          rm -rf "$HOME/.gitea/directedArticles/site"
          mkdir -p "$HOME/.gitea/directedArticles"
          cp -r site "$HOME/.gitea/directedArticles/site"
